//Products
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
//Product
export const LOADING_PRODUCT = 'LOADING_PRODUCT';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';
//Cart
export const ADD_CARTITEM = 'ADD_CARTITEM';
export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_QTYANDPRICE = 'CALCULATE_QTYANDPRICE';