//Products
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';

//Product
export const LOADING_PRODUCT = 'LOADING_PRODUCT';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';
export const LOADING_PRODUCTDELETE = 'LOADING_PRODUCTDELETE';
export const PRODUCTDELETE_SUCCESS = 'PRODUCTDELETE_SUCCESS';
export const PRODUCTDELETE_FAIL = 'PRODUCTDELETE_FAIL';
export const LOADING_PRODUCTCREATE = 'LOADING_PRODUCTCREATE';
export const PRODUCTCREATE_SUCCESS = 'PRODUCTCREATE_SUCCESS';
export const PRODUCTCREATE_FAIL = 'PRODUCTCREATE_FAIL';
export const PRODUCTCREATE_RESET = 'PRODUCTCREATE_RESET';
export const LOADING_PRODUCTUPDATE = 'LOADING_PRODUCTUPDATE';
export const PRODUCTUPDATE_SUCCESS = 'PRODUCTUPDATE_SUCCESS';
export const PRODUCTUPDATE_FAIL = 'PRODUCTUPDATE_FAIL';
export const PRODUCTUPDATE_RESET = 'PRODUCTUPDATE_RESET';

//Cart
export const ADD_CARTITEM = 'ADD_CARTITEM';
export const REMOVE_CARTITEM = 'REMOVE_CARTITEM';
export const CHANGE_QUANTITY = 'CHANGE_QUANTITY';
export const CALCULATE_TOTALQTYANDPRICE = 'CALCULATE_QTYANDPRICE';
export const CALCULATE_ITEMPRICE = 'CALCULATE_ITEMPRICE';
export const CALCULATE_TAXPRICE = 'CALCULATE_TAXPRICE';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const SAVE_PAYMENTMETHOD = 'SAVE_PAYMENTMETHOD';

//Auth
export const LOADING_AUTH = 'LOADING_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//User
export const LOADING_USERDATA = 'LOADING_USERDATA';
export const USERDATA_SUCCESS = 'USERDATA_SUCCESS';
export const USERDATA_FAIL = 'USERDATA_FAIL';
export const USERDATA_RESET = 'USERDATA_RESET';
export const LOADING_USERUPDATE = 'LOADING_USERUPDATE';
export const USERUPDATE_SUCCESS = 'USERUPDATE_SUCCESS';
export const USERUPDATE_FAIL = 'USERUPDATE_FAIL';
export const LOADING_USERORDERS = 'LOADING_USERORDERS';
export const USERORDERS_SUCCESS = 'USERORDERS_SUCCESS';
export const USERORDERS_FAIL = 'USERORDERS_FAIL';
export const USERORDERS_RESET = 'USERORDERS_RESET';
export const LOADING_USERLIST = 'LOADING_USERLIST';
export const USERLIST_SUCCESS = 'USERLIST_SUCCESS';
export const USERLIST_FAIL = 'USERLIST_FAIL';
export const LOADING_USERDELETE = 'LOADING_USERDELETE';
export const USERDELETE_SUCCESS = 'USERDELETE_SUCCESS';
export const USERDELETE_FAIL = 'USERDELETE_FAIL';

//Order
export const LOADING_ORDERCREATE = 'LOADING_ORDERCREATE';
export const ORDERCREATE_SUCCESS = 'ORDERCREATE_SUCCESS';
export const ORDERCREATE_FAIL = 'ORDERCREATE_FAIL';

export const LOADING_ORDERDETAIL = 'LOADING_ORDERDETAIL';
export const ORDERDETAIL_SUCCESS = 'ORDERDETAIL_SUCCESS';
export const ORDERDETAIL_FAIL = 'ORDERDETAIL_FAIL';

export const LOADING_ORDERPAID = 'LOADING_ORDERPAID';
export const ORDERPAID_SUCCESS = 'ORDERPAID_SUCCESS';
export const ORDERPAID_FAIL = 'ORDERPAID_FAIL';
export const ORDERPAID_RESET = 'ORDERPAID_RESET';

export const LOADING_ORDERLIST = 'LOADING_ORDERLIST';
export const ORDERLIST_SUCCESS = 'ORDERLIST_SUCCESS';
export const ORDERLIST_FAIL = 'ORDERLIST_FAIL';

export const LOADING_ORDERDELIVER = 'LOADING_ORDERDELIVER';
export const ORDERDELIVER_SUCCESS = 'ORDERDELIVER_SUCCESS';
export const ORDERDELIVER_FAIL = 'ORDERDELIVER_FAIL';
export const ORDERDELIVER_RESET = 'ORDERDELIVER_RESET';


//Review
export const LOADING_REVIEWLIST = 'LOADING_REVIEWLIST';
export const REVIEWLIST_SUCCESS = 'REVIEWLIST_SUCCESS';
export const REVIEWLIST_FAIL = 'REVIEWLIST_FAIL';

export const LOADING_REVIEWCREATE = 'LOADING_REVIEWCREATE';
export const REVIEWCREATE_SUCCESS = 'REVIEWCREATE_SUCCESS';
export const REVIEWCREATE_FAIL = 'REVIEWCREATE_FAIL';
export const REVIEWCREATE_RESET = 'REVIEWCREATE_RESET';